import type { Metadata } from "next";
import { Geist_Mono, Inter, Zain } from "next/font/google";
import Providers from "@/components/providers";
import { hasLocale } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { cn } from "@/lib/utils";
import Header from "@/components/layout/header";

/** Arabic — Zain (Google Fonts) */
const zain = Zain({
  subsets: ["arabic"],
  variable: "--font-zain",
  weight: ["400", "700", "800"],
});

/** English — Inter (readable UI) */
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-en",
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  const fontSansBody =
    locale === "ar"
      ? "var(--font-zain), system-ui, sans-serif"
      : "var(--font-en), ui-sans-serif, system-ui, sans-serif";

  return (
    <html
      lang={locale}
      dir={locale === "ar" ? "rtl" : "ltr"}
      className={cn(
        "h-full antialiased",
        zain.variable,
        inter.variable,
        geistMono.variable,
        locale === "ar" ? zain.className : inter.className,
      )}
      style={{ "--font-sans-body": fontSansBody } as React.CSSProperties}
    >
      <body>
        <Providers>
          <main className="flex min-h-screen min-w-0 flex-col overflow-x-hidden">
            <Header />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
